services:
  backend:
    build: .
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
