services:
  backend:
    build: .
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8123}:${APP_PORT:-8123}"
    command: sh -c "python -m uvicorn app.main:app --host 0.0.0.0 --port $${APP_PORT:-8123} --reload"
